version: '3.7'

services:
  minio:
    image: minio/minio
    container_name: minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - ./data:/data # Mount local directory for data persistence
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"

  # Optionally, include an alias for quicker access to MinIO CLI
  mc:
    image: minio/mc
    container_name: minio-client
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c '
      while ! nc -z minio 9000; do
        echo "Waiting for MinIO server...";
        sleep 2;
      done;
      /bin/sh'
